services:
  mongo:
    image: mongo:latest
    container_name: intern-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
